### ISSUE TITLE
THIS LOOKS SUPER  COOL, put it in the app store!

### ISSUE THREAD

**Issue by jospoortvliet** [MarkPartlett/dashboardcharts#1]
Hi Mark,

I just want to convince you to put this app in the app store. Let's see how many people agree with me :smile:

**Comment by ediazcomellas** [comment]
It is a fantastic tool.  I am sure it has tons of use cases.

**Comment by ediazcomellas** [comment]
Open a bounty  at https://www.bountysource.com/teams/nextcloud 

I will pledge.

**Comment by rakekniven** [comment]
Hello Mark,

please make your work available in the app store.

Thank you

**Comment by seventer** [comment]
Please do NOT add this to the app store. The license model of Highcharts is not good. Please choose another graphing library.

**Comment by MarkPartlett** [comment]
I've published v0.0.1 of dashboardcharts to the app store. There are CORS issues with the Highcharts Editor javascript component in the 'settings' tab. I'm was unable to define the CORS policy for the 'Settings' form. I've added specific domains to my default CORS policy for https://deskonline.cloud to get the functionality to work.

I purchased a "High-five License" from Highcharts.JS to cover my development. I believe the use of Highcharts is allowed for  "non commercial use" https://shop.highsoft.com/faq#Non-Commercial-0 . I was using Chart.js/Gauge.js/DataTables.js and some iframes in a previous version, but was concerned that they wouldn't be used without a good configuration tool. The code is still there, just not defined in the info.xml https://github.com/MarkPartlett/dashboardcharts/tree/master/templates/widgets

**Comment by ediazcomellas** [comment]
Thanks for your effort @MarkPartlett. 

I am a bit confused about the licensing model of this library. Obviously, Mark is not going to pay thousands of USD for an OEM license, and we can't purchase a "developer limiited" license because we do not know how many devs are working in this project. Is this a deadlock?

**Comment by jospoortvliet** [comment]
Looking at https://shop.highsoft.com/faq#Non-Commercial-0 - sadly, this isn't GPL compatible :sob: 
But good to know there are alternatives with Chart.js/Gauge.js/DataTables.js - even though they have limitations... let's make sure that a further release figures out the licensing thing - let's give this a chance for people to look at and contribute to, and look at alternative chart libraries together...  ???

Thanks for publishing, Mark!
