### ISSUE TITLE
Unable to activate

### ISSUE THREAD

**Issue by Pixxelfragger** [MarkPartlett/dashboardcharts#3]
After Downloading the App (Dashboard 6.0.0 is installed and running), when i try to activate the app i get following error message:

> An exception occurred while executing 'CREATE TABLE `oc_dashboard_data` (`user_id` VARCHAR(255) NOT NULL, `widget` VARCHAR(255) NOT NULL, `data` VARCHAR(10240) DEFAULT NULL, PRIMARY KEY(`user_id`, `widget`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by MarkPartlett** [comment]
It looks like a mysql/mariadb innodb issue with the primary index key being too long because of the support for emojis in utf8mb4. The solution is documented here : https://help.nextcloud.com/t/solved-syntax-error-or-access-violation-1071-specified-key-was-too-long-max-key-length-is-767-bytes/34740
